exclude: "^(setup/)|.pot$|.po$"
repos:
- repo: https://github.com/ambv/black
  rev: 19.3b0
  hooks:
  - id: black
    args: [--line-length=79, --target-version=py27]
    language_version: python3
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: debug-statements
  - id: flake8
    name: flake8 except __init__.py
    args: [--exclude=__init__.py]
    additional_dependencies: ["flake8-bugbear == 18.8.0"]
    language_version: python3
  - id: flake8
    name: flake8 only __init__.py
    args: [--ignore=E501 F401]  # ignore imported unused in __init__.py
    files: __init__.py
    language_version: python3
- repo: https://github.com/asottile/pyupgrade
  rev: v1.6.1
  hooks:
  - id: pyupgrade
    language_version: python3
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.3.0
  hooks:
  - id: seed-isort-config
    language_version: python3
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
    language_version: python3
